name: acme

profile: default

version: '1.0'

require-dbt-version: ">=0.13.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
  quote_columns: false

on-run-end:
  "{{ grant_select_on_schemas(schemas, 'reporter') }}"
